### PR TITLE
fix(ptoas): make vpto backend own tile op expansion

### LINKED ISSUE #162: [UX] vpto backend currently depends on --enable-tile-op-expand; suggest merging or auto-enabling
### Background

当前 `--pto-backend=vpto` 对一部分 tile-level op 实际上隐式依赖 `--enable-tile-op-expand`。

例如 `trowargmax` / `trowargmin` 这类 case，如果直接运行：

```bash
ptoas --pto-arch=a5 --pto-backend=vpto --vpto-emit-hivm-llvm <input.pto>
```

会因为高层 tile op 没有先展开成基础 VPTO IR，而在后续 LLVM export 阶段报错。

如果改成：

```bash
ptoas --pto-arch=a5 --pto-backend=vpto --enable-tile-op-expand --vpto-emit-hivm-llvm <input.pto>
```

则可以正常通过。

相关现状可见：#154

### Problem

从用户视角看，`--pto-backend=vpto` 像是在选择最终后端；但实际上一部分输入只有在额外加上 `--enable-tile-op-expand` 时才可用。

这导致：

- 选项之间存在隐式依赖，不容易从 CLI 语义上看出来
- 用户容易把报错误判成 lowering/LLVM emission bug
- 相同的 `vpto` 入口在不同 op 上行为不一致，增加排查成本

### Suggestion

建议考虑以下方向之一：

1. 当用户选择 `--pto-backend=vpto` 时，对需要 tile-op expand 的路径自动启用 `--enable-tile-op-expand`
2. 直接把两者合并成一个更明确的 `vpto` 编译入口，减少用户理解成本
3. 如果暂时不合并，至少在缺少 `--enable-tile-op-expand` 且检测到相关 tile-level op 时，给出显式诊断，提示需要开启该选项，而不是在 LLVM export 阶段以 `builtin.unrealized_conversion_cast` 形式失败

### Expected outcome

- `vpto` 路径的入口语义更清晰
- 减少因选项组合错误导致的误报 issue
- 把“编译路径选择问题”和“真实 lowering bug”更清楚地区分开

### PR DESCRIPTION
**Pull request by Zhendong404**
## Summary
- make TileOp expansion on the VPTO path depend on `--pto-backend=vpto` instead of `--enable-tile-op-expand`
- keep `--enable-tile-op-expand` as a deprecated compatibility flag with no behavioral effect
- extend the tadds VPTO regression to cover both plain `vpto` and the legacy compatibility flag

## Validation
- `ninja -C build ptoas`
- `build/tools/ptoas/ptoas --pto-arch=a5 --pto-backend=vpto --emit-vpto test/dsl/expand_tile_op_tilelang_tadds.pto -o - | FileCheck test/dsl/expand_tile_op_tilelang_tadds.pto`
- `build/tools/ptoas/ptoas --pto-arch=a5 --pto-backend=vpto --enable-tile-op-expand --emit-vpto test/dsl/expand_tile_op_tilelang_tadds.pto -o - | FileCheck test/dsl/expand_tile_op_tilelang_tadds.pto`

Closes #162

### CODE REVIEW

File: tools/ptoas/ptoas.cpp [hunk 1]
```diff
@@ -1501,7 +1517,7 @@ int main(int argc, char **argv) {
     if (failed(emitSharedPreBackendSeamIR(*module, ptoSeamIRFile)))
       return 1;
 
-    if (failed(lowerPTOToVPTOBackend(*module)))
+    if (failed(lowerPTOToVPTOBackend(*module, shouldEnableTileOpExpand)))
```
Comment (mouliangyu) [inline tools/ptoas/ptoas.cpp]: 这里实际本身就是在 vpto backend 控制下，看起来不需要再判断 effective backend 了

**Review by mouliangyu — CHANGES_REQUESTED** [review]

**Review by mouliangyu — APPROVED** [review]
